### ISSUE TITLE
References not supported for environmentalization

### ISSUE THREAD

**Issue by remisbaima** [Axway-API-Management-Plus/apigw-maven-plugin#37]
Hi,
Currently I have to manage many .ENV files manually. It is really painful and error prone. So I really loved when I found out about this project.
I tried to use it and I get a lot of errors like:
[ERROR] ValueError(u'Reference types are not supported for environmentalization: name=serverCert; index=0; type=reference;

Then I found your FAQ:
https://github.com/Axway-API-Management-Plus/apigw-maven-plugin/blob/master/doc/manual/_faq.adoc#why-are-references-not-supported-for-environmentalization

We have lots of references (since we encrypt end-to-end, including two-way SSL), so I just want to say that this is a show stopper for us.

**Comment by mlookaxw** [comment]
At my customer we also use mTLS connections and we configure it via the plugin.

The concept of changing the reference is to have all certificates in the project. On staging only the reference to the certificate will be changed.

For the plugin we have another approach. For each purpose a specific alias with the according certificate is created. On staging we don't change the reference, we change the certificate of the alias instead. So the alias will be named according to the purpose of the certificate (e.g. 'cassandra-client').

As we don't have to change references the limitation is not relevant for us. This has also the advantage that only required certificates will be part of the configured .fed files. No certificates from the development environment have to be part of the production .fed. Also no certificates from the production environment have to be part of the development project.

**Scenario**
A mTLS connection is required for the Cassandra connection. So a client certificate and a trusted CA certificate has to be configured.

**Solution**
In PolicyStudio add a client certificate for the mTLS connection. The alias of the certificate will be named "cassandra-client". For the trusted Cassandra certificate add a CA certificate with the alias name "cassandra-server-ca".

In the Cassandra configuration of PolicyStudio reference the alias "cassandra-client" as the client certificate and the "cassandra-server-ca" alias as the trusted certificate.

The plugin supports to replace certificates addressed by aliases. So on staging the certificate with the alias "cassandra-client" will be replaced with the stage specific client certificate. The same approach can be used for the "cassandra-server-ca".

**Comment by mlookaxw** [comment]
@remisbaima Is the limitation still a show stopper or does the workaround described in the previous comment solve your issues?

**Comment by remisbaima** [comment]
@mlookaxw : I still did not have the chance to test it, but it sounds like it would work. thanks.
