### ISSUE TITLE
Package and Deploy tools not sufficient for creating .fed file

### ISSUE THREAD

**Issue by woelkjulian** [Axway-API-Management-Plus/apigw-maven-plugin#38]
Hello,
nice plugin you have. Here is my setup:

- Axway API Management 7.7.0
- Linux CI Runner with package and deploy tools installed with the same version 7.7..0
- apigw-maven-plugin:0.11.1

I currently have the problem that Im not able to build deployment projects (.fed) file within the pipeline runners (see attached screenshot)
![jython_missing](https://user-images.githubusercontent.com/25659642/77531347-0f0d5000-6e93-11ea-9bdf-23b61ac84d7e.PNG)

As stated within your Wiki, only the package and deploy tools are a prerequesite, but the missing "jython" files for building the .fed file only come with the API Gateway installation, not with the package and deploy tools. 

Is there another way, or do I have to add the whole API Gateway installation to the CI Runner? I mean apart from the 800 MB on top its more about arguing with the team thats managing the CI why we need to install the whole Gateway solution for just building our configuration.

Greetings

**Comment by mlookaxw** [comment]
Sorry for the delay.

I mainly tested the plugin with the Windows package and deploy tools. There the "jython" files are part of the installation.

I have to check the Linux installation of the package and deploy tools.

Stay tuned...

**Comment by mlookaxw** [comment]
@woelkjulian you are right, the `jython` startup script is not part of the "Package & Deployment Tool" (for whatever reason).

You could copy it from a full installation or just create it manually.

**Manual Creation**
Creat a file $AXWAY_HOME/apigateway/posix/bin/jython with the content below and make it executable.

```
#!/bin/sh
. `dirname "$0"`/../lib/venv "$0"
component=`basename "$0"`
. `dirname "$0"`/../lib/venv-ld_preload
exec "$V_PLATFORM_BIN/vshell" -e "$VDISTDIR/system/conf/$component.xml" "$@"
```

**Comment by mlookaxw** [comment]
This is not an issue of the plugin. It's an issue of the installer package provided with the API Gateway. Therefore the issue will be closed.

This will be solved with future releases of the API Gateway/Manager. In the meantime you can use the workaround described in the previous comment.

**Comment by woelkjulian** [comment]
Thanks for the information!
