### ISSUE TITLE
How to auto-generate the gateway.certs.json?

### ISSUE THREAD

**Issue by remisbaima** [Axway-API-Management-Plus/apigw-maven-plugin#42]
I could not find in the documentation any way to auto-generate the gateway.certs.json
Similar to what happen with the "gateway.config.json", I was expecting to have it auto generated either from a "/certs" dir containing e.g. .PEM or .CRT files or from the certs inside my server project.

**Comment by mlookaxw** [comment]
The "gateway.certs.json" will be autogenerated from the certs inside your project.

For generation you have to specify the file via the `pom.xml` or via the command line parameter of the `buildfed` tool.

For the pom.xml you have to add the `<configCertsFile>` element to the plugin configuration (see [Plugin Configuration](https://github.com/Axway-API-Management-Plus/apigw-maven-plugin/blob/master/doc/manual/_reference.adoc#plugin-configuration))

For the `buildfed` tool you have to specify the `--cert` parameter (see [Build FED](https://github.com/Axway-API-Management-Plus/apigw-maven-plugin/blob/master/doc/manual/_config-tool.adoc#build-fed)).

**Comment by remisbaima** [comment]
Hi,
thanks for the quick reply.
I was using the `<configCertsFile>` and it was not being generated.
But I found my issue: since I was running for the first time to generate the gateway.config.json, the build was failing probably before it could get to the gateway.certs.json generation:
`[ERROR] Configuration of entities failed; check JSON configuration for unconfigured entity fields!`
