### ISSUE TITLE
Is axway.config.secrets.passphrase still supported?

### ISSUE THREAD

**Issue by remisbaima** [Axway-API-Management-Plus/apigw-maven-plugin#43]
It is documented here, but seems to not work: https://github.com/Axway-API-Management-Plus/apigw-maven-plugin/blob/master/doc/manual/_usage.adoc

**Comment by mlookaxw** [comment]
It's a bug in the documentation.

For security reasons the passphrase for secrets is not supported. The passphrase is replaced by a key file which can be specified by the `axway.config.secrets.key` property or the `<configSecretsKey>` configuration (see [Reference](https://github.com/Axway-API-Management-Plus/apigw-maven-plugin/blob/master/doc/manual/_reference.adoc#plugin-configuration))

I'll fix the documentation.
