### ISSUE TITLE
Certificate replaces in different environments

### ISSUE THREAD

**Issue by kunwardhwaj** [Axway-API-Management-Plus/apigw-maven-plugin#44]
Hello,

We have four different environment starting from Dev to Prod. I would like to standardize the promotion of code and environment settings including certificates to the upper environments. 

While promoting to Stage from Dev,  I  would like to replace the existing Dev listeners certs to reflect Stage certs. I am wondering if we can do something like below :

"Dev-1-p12": {
            "origin": {
                "info": {
                    "not_after": "2020-05-21T07:02:00+02:00",
                    "subject": "CN=Dev1, O=Axway, L=Berlin, ST=Berlin, C=DE"
                }
            },
            "update": {
                "file": "cert/Stage.p12",
                "password": "server", 
                "source": "password", 
                "type": "p12"
            }
        },

Does the existing plugin already supports this or we can add it as an enhancement ?

**Comment by mlookaxw** [comment]
Yes, the plugin supports to replace certificates.

So you can use different certificates for different stages.

The plugin also has to option to set a base directory for certificates. So one single certificate configuration file can be used. For different stages you can just change the base directory.

**Comment by kunwardhwaj** [comment]
Thanks! for some reason when I am trying below replace, it is giving me an error. Do you know what could be wrong here ?

**error message** : ValueError(u"Certificate update not configured for alias 'CN=api-int.xxxx'!",) 

"api-int.xxxx_alias": {
      "origin": {
        "info": {
          "not_after": "2021-04-24T23:59:59Z",
          "subject": "CN=api-int.xxxx, OU=YYYY, O=\"ZZZZ\", STREET=TTTT L=PPPP, ST=CA"
        }
      },
      "update": {
        "file": "config/dev/certs/Dev.p12",
        "password": "dev.password",
        "source": "secrets",
        "type": "p12"
      }
    }

**Comment by kunwardhwaj** [comment]
you can ignore my previous comment. It was an issue with my configuration.
