### ISSUE TITLE
Fature request: add support for multiple gateway.certs.json files

### ISSUE THREAD

**Issue by remisbaima** [Axway-API-Management-Plus/apigw-maven-plugin#49]
Use case: we have many CAs that are common to all environments and only the private certs are different for each environment.
So being able to provide multiple gateway.certs.json files would allow us to put all common CAs in 1 single common/shared file.
It would be equal to what we can do with the `<configPropertyFiles>`: https://github.com/Axway-API-Management-Plus/apigw-maven-plugin/blob/master/doc/manual/_usage.adoc#configure-properties

**Comment by mlookaxw** [comment]
The handling of the certificate configuration files differs from the handling of the property files.

Property files are not updated by the plugin and therefore it was easy to split the configuration into multiple files.

The certificate configuration files are generated/updated according to the used certificates. If the configuration is split over multiple files it's hard to decide which file has to be updated.

**Comment by mlookaxw** [comment]
@remisbaima the new release 1.2.0 supports multiple base directories for certificates.

The parameter `--base-dir` can be specified multiple times. The directories will be scanned for certificate files. So, common certificates can be placed in a separate folder and can be shared by all environments.
