### ISSUE TITLE
Configuring env specific jwt signer certificates

### ISSUE THREAD

**Issue by jkunjiporinchu** [Axway-API-Management-Plus/apigw-maven-plugin#61]
I am trying to configure env specific jwt signer certificate. As the maven plugin does not allow environmentalization of referenced fields, can you please suggest how we can get past this.

**Comment by mlookaxw** [comment]
The concepts for certificates is, that dummy certificates are created in PolicyStudio (especially for private keys).
The alias of the certificate should express the purpose of the certificate. During the staging process the certificate will be replace.

See also [How to work with certificates](https://github.com/Axway-API-Management-Plus/apigw-maven-plugin/blob/master/doc/manual/_faq.adoc#how-to-work-with-certificates) and [Config Tool examples](https://github.com/Axway-API-Management-Plus/apigw-maven-plugin/tree/master/example/config-tool).

**Comment by mlookaxw** [comment]
I hope your question is answered. In case of further questions, please reopen the issue.
