### ISSUE TITLE
Getting errors when trying to deploy

### ISSUE THREAD

**Issue by enriquevanderberg** [Axway-API-Management-Plus/apigw-maven-plugin#66]
Good day,

Would you please be able to assist with the below issues I'm encountering in regards to the plugin.

1. I was trying to follow along the example project that was given and tried to deploy it to our running gateway container to get a feel for the plugin but I'm running into the below 405 error when trying to deploy.

![image](https://github.com/Axway-API-Management-Plus/apigw-maven-plugin/assets/152380639/2f20c5f8-18d4-4564-9023-443dc94bf3b6)

2. Can you deploy the policy archive project on its own? because I ran into a configuration is null error when trying to do so. I'm not sure what configuration file its complaining about.

Kind Regards,
Enrique

**Comment by mlookaxw** [comment]
You are trying to the deploy the project to an EMT (container based) environment.

For EMT, deployment via `projdeploy` or `managedomain` is not supported (this is an restriction of EMT). Even if `EMT_DEPLOYMENT_ENABLED` is true, projects can be deployed via Policy Studio only. As the plugin is using `projdeploy`, for EMT, the `deploy`goal is not supported by the plugin.

**Comment by enriquevanderberg** [comment]
Hi Martin,

We deployed the containers with EMT_DEPLOYMENT_ENABLED set to false.
![image](https://github.com/Axway-API-Management-Plus/apigw-maven-plugin/assets/152380639/d2443e80-508c-4b1f-be61-c3956057a28f)

Kind Regards,

**Comment by mlookaxw** [comment]
Disabling EMT deployment is the standard, as deployments will not survive restarts. So deployment to EMT via Policy Studio is only for testing purpose.

Nevertheless, direct deployment to EMT is not supported by the Maven plugin.

**Comment by mlookaxw** [comment]
For EMT, the plugin can be used to build the server project artifact and to build a configured FED file (`/merge/fed`) with the `buildfed` utility (which is provided by the project).
